### ISSUE TITLE
Is there any API of the three *.a file generated by building libquic?

### ISSUE THREAD

**Issue by pengkunlunHIT** [devsisters/libquic#12]
libquic.a, libssl.a, libcrypto.a are generated after building libquic.
I know .a file is static library,and I  have also seen goquic and gospdyquic.These project use the libquic as a base,and there are the .a files in goquic's lib file.   
But how to use these  .a files? Is there any API which introduce the provided function detailedly?

**Comment by serialx** [comment]
Unfortunately no. We don't have any documentation. Since the codes are all from Chromium codebase, you can look at the sample server and client implementation from Chromium and get some glimpse on how they work. These samples won't work with `libquic` however. They rely heavily on message loop and socket implementation on Chromium, which we didn't extract.

This library currently exists to aid independent development away from Chromium build system.

We have plans to make example C++ server and client, but current situation is very raw. So please bear with us. Thank you.

**Comment by pengkunlunHIT** [comment]
Thank you for you reply.I believe the job of libquic is a great work and i really appreciate your help.
Good luck,fighting!
