### ISSUE TITLE
Faild to build libquic in ubuntu-64bit

### ISSUE THREAD

**Issue by chqiwang** [devsisters/libquic#5]
I try to build the project on Ubuntu 64bit, but every time when make reach 89%, the machine will reboot. Did you see this happend? (32bit is OK and I do my work in VMware Workstation)

**Comment by serialx** [comment]
Hello, our main development environment was Ubuntu 64bit, so it should build without any problems. Please have a look at your machine's configuration. Since the build process fully loads the processor, the build process may have overheated your processor. Processor overheat is one of the common reason of unscheduled reboots. You may want to try `ninja -j 1` or `make -j 1` and see if it alleviates the problem.

Thanks!

**Comment by chqiwang** [comment]
Thank you! I will try later.

**Comment by chqiwang** [comment]
The command 'make -j 1' solved my problem! Thank you!
